//
//  AlbumListConfigurator.swift
//  CleanSwiftTest
//
//  Created by anoop mohanan on 25/03/17.
//  Copyright (c) 2017 anoop mohanan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension AlbumListViewController: AlbumListPresenterOutput
{
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
}

extension AlbumListInteractor: AlbumListViewControllerOutput
{
}

extension AlbumListPresenter: AlbumListInteractorOutput
{
}

class AlbumListConfigurator
{
  // MARK: - Object lifecycle
  
  static let sharedInstance = AlbumListConfigurator()
  
  private init() {}
  
  // MARK: - Configuration
  
  func configure(viewController: AlbumListViewController)
  {
    let router = AlbumListRouter()
    router.viewController = viewController
    
    let presenter = AlbumListPresenter()
    presenter.output = viewController
    
    let interactor = AlbumListInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
