//
//  AlbumListInteractor.swift
//  CleanSwiftTest
//
//  Created by anoop mohanan on 25/03/17.
//  Copyright (c) 2017 anoop mohanan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AlbumListInteractorInput
{
  func fetchAlbums(request: AlbumList.Something.Request)
    var albums: [Album] { get }
}

protocol AlbumListInteractorOutput
{
  func presentSomething(response: AlbumList.Something.Response)
}

class AlbumListInteractor: AlbumListInteractorInput
{
  var output: AlbumListInteractorOutput!
  var worker: AlbumListWorker = AlbumListWorker(albumStore: AlbumStore())

  var albums: [Album] = []
  // MARK: - Business logic
  
  func fetchAlbums(request: AlbumList.Something.Request)
  {

        // NOTE: Pass the result to the Presenter
    worker.fetchMeTheAblums {[weak self] (data) in
        self?.albums = data
        let response = AlbumList.Something.Response(albums: data)
        self?.output.presentSomething(response: response)
    }

  }
}
