//
//  AlbumListWorker.swift
//  CleanSwiftTest
//
//  Created by anoop mohanan on 25/03/17.
//  Copyright (c) 2017 anoop mohanan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class AlbumListWorker
{
  // MARK: - Business Logic
    var albumStore:AlbumStore
  
    init(albumStore:AlbumStore) {
        self.albumStore = albumStore
    }
    func fetchMeTheAblums(completion:@escaping (_ albums:[Album])->Void){
        
        albumStore.fetchAlbumDetails { (data) in
            completion(data)
        }
    }

}
