//
//  AlbumListPresenter.swift
//  CleanSwiftTest
//
//  Created by anoop mohanan on 25/03/17.
//  Copyright (c) 2017 anoop mohanan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol AlbumListPresenterInput
{
  func presentSomething(response: AlbumList.Something.Response)
}

protocol AlbumListPresenterOutput: class
{
  func displaySomething(viewModel: AlbumList.Something.ViewModel)
}

class AlbumListPresenter: AlbumListPresenterInput
{
  weak var output: AlbumListPresenterOutput!
  
  // MARK: - Presentation logic
  
  func presentSomething(response: AlbumList.Something.Response)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    var albumArray:[AlbumList.Something.ViewModel.Album] = []
    for album in response.albums{
        let albumVM = AlbumList.Something.ViewModel.Album(title: album.title, artist: album.artist, url: album.url!, imageUrl: album.imageUrl!, thumbNailUrl: album.thumbNailUrl!)
        albumArray.append(albumVM)
    }
    let viewModel = AlbumList.Something.ViewModel(albumList: albumArray)
    output.displaySomething(viewModel: viewModel)
  }
}
