//
//  AlbumListModels.swift
//  CleanSwiftTest
//
//  Created by anoop mohanan on 25/03/17.
//  Copyright (c) 2017 anoop mohanan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct AlbumList
{
  struct Something
  {
    struct Request
    {
    }
    struct Response
    {
        var albums: [Album]
    }
    struct ViewModel
    {
        // View model to hold details of each album
        struct Album {
            var title:String
            var artist:String
            var url:String
            var imageUrl:String
            var thumbNailUrl:String
        }
        // List which store Album VMs
        var albumList:[Album]

    }
  }
}
