//
//  DetailsInteractor.swift
//  CleanSwiftTest
//
//  Created by anoop mohanan on 27/03/17.
//  Copyright (c) 2017 anoop mohanan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol DetailsInteractorInput
{
  func doSomething(request: Details.Something.Request)
     var albums: Album! { get set}
}

protocol DetailsInteractorOutput
{
  func presentSomething(response: Details.Something.Response)
}

class DetailsInteractor: DetailsInteractorInput
{
    internal var albums: Album!

  var output: DetailsInteractorOutput!
  var worker: DetailsWorker!
  
  // MARK: - Business logic
  
  func doSomething(request: Details.Something.Request)
  {
    // NOTE: Create some Worker to do the work
    
    worker = DetailsWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = Details.Something.Response()
    output.presentSomething(response: response)
  }
}
