//
//  DetailsWorker.swift
//  CleanSwiftTest
//
//  Created by anoop mohanan on 27/03/17.
//  Copyright (c) 2017 anoop mohanan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class DetailsWorker
{
  // MARK: - Business Logic
  
  func doSomeWork()
  {
    // NOTE: Do the work
  }
}
